#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
compton --config $HOME/.config/compton/compton.conf &
feh --bg-fill $HOME/Imágenes/fondos/mrrobot.jpg &
$HOME/.config/polybar/launch.sh --cuts &
killall mate-notification-daemon; dunst &
wname L3GD &

bspc config pointer_modifier mod1
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a burp-StartBurp: state=floating
bspc rule -a Display-im6.q16 state=floating follow=on
bspc rule -a Bitwarden state=floating follow=on
bspc rule -a Org.gnome.Nautilus state=floating follow=on
